name: "health-check: Build Tag Push"

on:
  push:
    branches:
      - main
    paths:
      - health-check/**

env:
  #REPO_NAME: yadyedida
  REPO_NAME: localhost:5000
  IMAGE_NAME: health-check
  LOCAL_REPO: true

jobs:
  build-and-push:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    environment: prd

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      if: env.LOCAL_REPO == 'false'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker Buildx (optional, but recommended for advanced builds X86/ARM)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Build, tag, and push the Docker image
    - name: "health-check: Build Tag Push"
      uses: docker/build-push-action@v4
      with:
        context: ./${{ env.IMAGE_NAME }}
        push: true
        tags: |
          ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref }}-${{ github.run_number }}
